plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\vdasilva\\Documents\\projects\\Tournament-Manager\\web-build"
publishOrigin = "ui"
command = "npx expo export:web"
commandOrigin = "ui"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]